# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import recovery_pb2 as recovery__pb2


class RecoveryStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.sendHoleInfo = channel.unary_unary(
        '/Recovery/sendHoleInfo',
        request_serializer=recovery__pb2.SendHoleInfoRequest.SerializeToString,
        response_deserializer=recovery__pb2.SendHoleInfoReply.FromString,
        )
    self.sendWholeMesh = channel.unary_unary(
        '/Recovery/sendWholeMesh',
        request_serializer=recovery__pb2.SendWholeMeshRequest.SerializeToString,
        response_deserializer=recovery__pb2.SendWholeMeshReply.FromString,
        )
    self.startRecovery = channel.unary_unary(
        '/Recovery/startRecovery',
        request_serializer=recovery__pb2.StartRecoveryRequest.SerializeToString,
        response_deserializer=recovery__pb2.StartRecoveryReply.FromString,
        )


class RecoveryServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def sendHoleInfo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def sendWholeMesh(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def startRecovery(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RecoveryServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'sendHoleInfo': grpc.unary_unary_rpc_method_handler(
          servicer.sendHoleInfo,
          request_deserializer=recovery__pb2.SendHoleInfoRequest.FromString,
          response_serializer=recovery__pb2.SendHoleInfoReply.SerializeToString,
      ),
      'sendWholeMesh': grpc.unary_unary_rpc_method_handler(
          servicer.sendWholeMesh,
          request_deserializer=recovery__pb2.SendWholeMeshRequest.FromString,
          response_serializer=recovery__pb2.SendWholeMeshReply.SerializeToString,
      ),
      'startRecovery': grpc.unary_unary_rpc_method_handler(
          servicer.startRecovery,
          request_deserializer=recovery__pb2.StartRecoveryRequest.FromString,
          response_serializer=recovery__pb2.StartRecoveryReply.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Recovery', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
