# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recovery.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='recovery.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0erecovery.proto\"5\n\x13SendHoleInfoRequest\x12\x0b\n\x03pos\x18\x01 \x01(\t\x12\x11\n\tneighbors\x18\x02 \x01(\t\"\x13\n\x11SendHoleInfoReply\"\x16\n\x14SendWholeMeshRequest\"\'\n\x12SendWholeMeshReply\x12\x11\n\twholemesh\x18\x01 \x01(\t\"6\n\x14StartRecoveryRequest\x12\x0b\n\x03pos\x18\x01 \x01(\t\x12\x11\n\tneighbors\x18\x02 \x01(\t\"\x14\n\x12StartRecoveryReply2\xc4\x01\n\x08Recovery\x12:\n\x0csendHoleInfo\x12\x14.SendHoleInfoRequest\x1a\x12.SendHoleInfoReply\"\x00\x12=\n\rsendWholeMesh\x12\x15.SendWholeMeshRequest\x1a\x13.SendWholeMeshReply\"\x00\x12=\n\rstartRecovery\x12\x15.StartRecoveryRequest\x1a\x13.StartRecoveryReply\"\x00\x62\x06proto3')
)




_SENDHOLEINFOREQUEST = _descriptor.Descriptor(
  name='SendHoleInfoRequest',
  full_name='SendHoleInfoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='SendHoleInfoRequest.pos', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neighbors', full_name='SendHoleInfoRequest.neighbors', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=71,
)


_SENDHOLEINFOREPLY = _descriptor.Descriptor(
  name='SendHoleInfoReply',
  full_name='SendHoleInfoReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=73,
  serialized_end=92,
)


_SENDWHOLEMESHREQUEST = _descriptor.Descriptor(
  name='SendWholeMeshRequest',
  full_name='SendWholeMeshRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=116,
)


_SENDWHOLEMESHREPLY = _descriptor.Descriptor(
  name='SendWholeMeshReply',
  full_name='SendWholeMeshReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='wholemesh', full_name='SendWholeMeshReply.wholemesh', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=118,
  serialized_end=157,
)


_STARTRECOVERYREQUEST = _descriptor.Descriptor(
  name='StartRecoveryRequest',
  full_name='StartRecoveryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos', full_name='StartRecoveryRequest.pos', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='neighbors', full_name='StartRecoveryRequest.neighbors', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=159,
  serialized_end=213,
)


_STARTRECOVERYREPLY = _descriptor.Descriptor(
  name='StartRecoveryReply',
  full_name='StartRecoveryReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=215,
  serialized_end=235,
)

DESCRIPTOR.message_types_by_name['SendHoleInfoRequest'] = _SENDHOLEINFOREQUEST
DESCRIPTOR.message_types_by_name['SendHoleInfoReply'] = _SENDHOLEINFOREPLY
DESCRIPTOR.message_types_by_name['SendWholeMeshRequest'] = _SENDWHOLEMESHREQUEST
DESCRIPTOR.message_types_by_name['SendWholeMeshReply'] = _SENDWHOLEMESHREPLY
DESCRIPTOR.message_types_by_name['StartRecoveryRequest'] = _STARTRECOVERYREQUEST
DESCRIPTOR.message_types_by_name['StartRecoveryReply'] = _STARTRECOVERYREPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendHoleInfoRequest = _reflection.GeneratedProtocolMessageType('SendHoleInfoRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDHOLEINFOREQUEST,
  '__module__' : 'recovery_pb2'
  # @@protoc_insertion_point(class_scope:SendHoleInfoRequest)
  })
_sym_db.RegisterMessage(SendHoleInfoRequest)

SendHoleInfoReply = _reflection.GeneratedProtocolMessageType('SendHoleInfoReply', (_message.Message,), {
  'DESCRIPTOR' : _SENDHOLEINFOREPLY,
  '__module__' : 'recovery_pb2'
  # @@protoc_insertion_point(class_scope:SendHoleInfoReply)
  })
_sym_db.RegisterMessage(SendHoleInfoReply)

SendWholeMeshRequest = _reflection.GeneratedProtocolMessageType('SendWholeMeshRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDWHOLEMESHREQUEST,
  '__module__' : 'recovery_pb2'
  # @@protoc_insertion_point(class_scope:SendWholeMeshRequest)
  })
_sym_db.RegisterMessage(SendWholeMeshRequest)

SendWholeMeshReply = _reflection.GeneratedProtocolMessageType('SendWholeMeshReply', (_message.Message,), {
  'DESCRIPTOR' : _SENDWHOLEMESHREPLY,
  '__module__' : 'recovery_pb2'
  # @@protoc_insertion_point(class_scope:SendWholeMeshReply)
  })
_sym_db.RegisterMessage(SendWholeMeshReply)

StartRecoveryRequest = _reflection.GeneratedProtocolMessageType('StartRecoveryRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTRECOVERYREQUEST,
  '__module__' : 'recovery_pb2'
  # @@protoc_insertion_point(class_scope:StartRecoveryRequest)
  })
_sym_db.RegisterMessage(StartRecoveryRequest)

StartRecoveryReply = _reflection.GeneratedProtocolMessageType('StartRecoveryReply', (_message.Message,), {
  'DESCRIPTOR' : _STARTRECOVERYREPLY,
  '__module__' : 'recovery_pb2'
  # @@protoc_insertion_point(class_scope:StartRecoveryReply)
  })
_sym_db.RegisterMessage(StartRecoveryReply)



_RECOVERY = _descriptor.ServiceDescriptor(
  name='Recovery',
  full_name='Recovery',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=238,
  serialized_end=434,
  methods=[
  _descriptor.MethodDescriptor(
    name='sendHoleInfo',
    full_name='Recovery.sendHoleInfo',
    index=0,
    containing_service=None,
    input_type=_SENDHOLEINFOREQUEST,
    output_type=_SENDHOLEINFOREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='sendWholeMesh',
    full_name='Recovery.sendWholeMesh',
    index=1,
    containing_service=None,
    input_type=_SENDWHOLEMESHREQUEST,
    output_type=_SENDWHOLEMESHREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='startRecovery',
    full_name='Recovery.startRecovery',
    index=2,
    containing_service=None,
    input_type=_STARTRECOVERYREQUEST,
    output_type=_STARTRECOVERYREPLY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_RECOVERY)

DESCRIPTOR.services_by_name['Recovery'] = _RECOVERY

# @@protoc_insertion_point(module_scope)
