# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: storage.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='storage.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\rstorage.proto\"\x1d\n\x0c\x43hunkRequest\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\" \n\rHashIdRequest\x12\x0f\n\x07hash_id\x18\x01 \x01(\t\"\"\n\x0fResponseBoolean\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xbe\x01\n\nFileServer\x12:\n\x13upload_chunk_stream\x12\r.ChunkRequest\x1a\x10.ResponseBoolean\"\x00(\x01\x12\x38\n\x13upload_single_chunk\x12\r.ChunkRequest\x1a\x10.ResponseBoolean\"\x00\x12:\n\x15\x64ownload_chunk_stream\x12\x0e.HashIdRequest\x1a\r.ChunkRequest\"\x00\x30\x01\x62\x06proto3')
)




_CHUNKREQUEST = _descriptor.Descriptor(
  name='ChunkRequest',
  full_name='ChunkRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='chunk', full_name='ChunkRequest.chunk', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=46,
)


_HASHIDREQUEST = _descriptor.Descriptor(
  name='HashIdRequest',
  full_name='HashIdRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash_id', full_name='HashIdRequest.hash_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=80,
)


_RESPONSEBOOLEAN = _descriptor.Descriptor(
  name='ResponseBoolean',
  full_name='ResponseBoolean',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='success', full_name='ResponseBoolean.success', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=116,
)

DESCRIPTOR.message_types_by_name['ChunkRequest'] = _CHUNKREQUEST
DESCRIPTOR.message_types_by_name['HashIdRequest'] = _HASHIDREQUEST
DESCRIPTOR.message_types_by_name['ResponseBoolean'] = _RESPONSEBOOLEAN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ChunkRequest = _reflection.GeneratedProtocolMessageType('ChunkRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHUNKREQUEST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:ChunkRequest)
  })
_sym_db.RegisterMessage(ChunkRequest)

HashIdRequest = _reflection.GeneratedProtocolMessageType('HashIdRequest', (_message.Message,), {
  'DESCRIPTOR' : _HASHIDREQUEST,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:HashIdRequest)
  })
_sym_db.RegisterMessage(HashIdRequest)

ResponseBoolean = _reflection.GeneratedProtocolMessageType('ResponseBoolean', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEBOOLEAN,
  '__module__' : 'storage_pb2'
  # @@protoc_insertion_point(class_scope:ResponseBoolean)
  })
_sym_db.RegisterMessage(ResponseBoolean)



_FILESERVER = _descriptor.ServiceDescriptor(
  name='FileServer',
  full_name='FileServer',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=119,
  serialized_end=309,
  methods=[
  _descriptor.MethodDescriptor(
    name='upload_chunk_stream',
    full_name='FileServer.upload_chunk_stream',
    index=0,
    containing_service=None,
    input_type=_CHUNKREQUEST,
    output_type=_RESPONSEBOOLEAN,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='upload_single_chunk',
    full_name='FileServer.upload_single_chunk',
    index=1,
    containing_service=None,
    input_type=_CHUNKREQUEST,
    output_type=_RESPONSEBOOLEAN,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='download_chunk_stream',
    full_name='FileServer.download_chunk_stream',
    index=2,
    containing_service=None,
    input_type=_HASHIDREQUEST,
    output_type=_CHUNKREQUEST,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FILESERVER)

DESCRIPTOR.services_by_name['FileServer'] = _FILESERVER

# @@protoc_insertion_point(module_scope)
