# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import storage_pb2 as storage__pb2


class FileServerStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.upload_chunk_stream = channel.stream_unary(
        '/FileServer/upload_chunk_stream',
        request_serializer=storage__pb2.ChunkRequest.SerializeToString,
        response_deserializer=storage__pb2.ResponseBoolean.FromString,
        )
    self.upload_single_chunk = channel.unary_unary(
        '/FileServer/upload_single_chunk',
        request_serializer=storage__pb2.ChunkRequest.SerializeToString,
        response_deserializer=storage__pb2.ResponseBoolean.FromString,
        )
    self.download_chunk_stream = channel.unary_stream(
        '/FileServer/download_chunk_stream',
        request_serializer=storage__pb2.HashIdRequest.SerializeToString,
        response_deserializer=storage__pb2.ChunkRequest.FromString,
        )


class FileServerServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def upload_chunk_stream(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def upload_single_chunk(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def download_chunk_stream(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_FileServerServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'upload_chunk_stream': grpc.stream_unary_rpc_method_handler(
          servicer.upload_chunk_stream,
          request_deserializer=storage__pb2.ChunkRequest.FromString,
          response_serializer=storage__pb2.ResponseBoolean.SerializeToString,
      ),
      'upload_single_chunk': grpc.unary_unary_rpc_method_handler(
          servicer.upload_single_chunk,
          request_deserializer=storage__pb2.ChunkRequest.FromString,
          response_serializer=storage__pb2.ResponseBoolean.SerializeToString,
      ),
      'download_chunk_stream': grpc.unary_stream_rpc_method_handler(
          servicer.download_chunk_stream,
          request_deserializer=storage__pb2.HashIdRequest.FromString,
          response_serializer=storage__pb2.ChunkRequest.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'FileServer', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
