# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import traversal_pb2 as traversal__pb2


class TraversalStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.ReceiveData = channel.unary_unary(
        '/traversal.Traversal/ReceiveData',
        request_serializer=traversal__pb2.ReceiveDataRequest.SerializeToString,
        response_deserializer=traversal__pb2.ReceiveDataResponse.FromString,
        )
    self.RespondData = channel.unary_unary(
        '/traversal.Traversal/RespondData',
        request_serializer=traversal__pb2.ResponseDataRequest.SerializeToString,
        response_deserializer=traversal__pb2.ResponseDataResponse.FromString,
        )
    self.SendData = channel.unary_unary(
        '/traversal.Traversal/SendData',
        request_serializer=traversal__pb2.SendDataRequest.SerializeToString,
        response_deserializer=traversal__pb2.SendDataResponse.FromString,
        )


class TraversalServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def ReceiveData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def RespondData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SendData(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_TraversalServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'ReceiveData': grpc.unary_unary_rpc_method_handler(
          servicer.ReceiveData,
          request_deserializer=traversal__pb2.ReceiveDataRequest.FromString,
          response_serializer=traversal__pb2.ReceiveDataResponse.SerializeToString,
      ),
      'RespondData': grpc.unary_unary_rpc_method_handler(
          servicer.RespondData,
          request_deserializer=traversal__pb2.ResponseDataRequest.FromString,
          response_serializer=traversal__pb2.ResponseDataResponse.SerializeToString,
      ),
      'SendData': grpc.unary_unary_rpc_method_handler(
          servicer.SendData,
          request_deserializer=traversal__pb2.SendDataRequest.FromString,
          response_serializer=traversal__pb2.SendDataResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'traversal.Traversal', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
