# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: traversal.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='traversal.proto',
  package='traversal',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x0ftraversal.proto\x12\ttraversal\"u\n\x12ReceiveDataRequest\x12\x0f\n\x07hash_id\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\r\n\x05stack\x18\x03 \x01(\t\x12\x0f\n\x07visited\x18\x04 \x01(\t\x12\x1a\n\x12requesting_node_ip\x18\x05 \x01(\t\"\xb5\x01\n\x13ReceiveDataResponse\x12\x46\n\x06status\x18\x01 \x01(\x0e\x32\x36.traversal.ReceiveDataResponse.TraversalResponseStatus\x12\x12\n\nfile_bytes\x18\x02 \x01(\x0c\"B\n\x17TraversalResponseStatus\x12\t\n\x05\x46OUND\x10\x00\x12\r\n\tFORWARDED\x10\x01\x12\r\n\tNOT_FOUND\x10\x02\"l\n\x13ResponseDataRequest\x12\x12\n\nfile_bytes\x18\x01 \x01(\t\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x0f\n\x07node_ip\x18\x03 \x01(\t\x12\x0e\n\x06status\x18\x04 \x01(\t\x12\x0c\n\x04path\x18\x05 \x01(\t\"\xa3\x01\n\x14ResponseDataResponse\x12G\n\x06status\x18\x01 \x01(\x0e\x32\x37.traversal.ResponseDataResponse.TraversalResponseStatus\"B\n\x17TraversalResponseStatus\x12\t\n\x05\x46OUND\x10\x00\x12\r\n\tFORWARDED\x10\x01\x12\r\n\tNOT_FOUND\x10\x02\"Q\n\x0fSendDataRequest\x12\x12\n\nfile_bytes\x18\x01 \x01(\x0c\x12\x12\n\nrequest_id\x18\x02 \x01(\t\x12\x16\n\x0e\x63lient_node_ip\x18\x03 \x01(\t\"\x12\n\x10SendDataResponse2\xf2\x01\n\tTraversal\x12N\n\x0bReceiveData\x12\x1d.traversal.ReceiveDataRequest\x1a\x1e.traversal.ReceiveDataResponse0\x01\x12N\n\x0bRespondData\x12\x1e.traversal.ResponseDataRequest\x1a\x1f.traversal.ResponseDataResponse\x12\x45\n\x08SendData\x12\x1a.traversal.SendDataRequest\x1a\x1b.traversal.SendDataResponse(\x01\x62\x06proto3')
)



_RECEIVEDATARESPONSE_TRAVERSALRESPONSESTATUS = _descriptor.EnumDescriptor(
  name='TraversalResponseStatus',
  full_name='traversal.ReceiveDataResponse.TraversalResponseStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FOUND', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORWARDED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_FOUND', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=265,
  serialized_end=331,
)
_sym_db.RegisterEnumDescriptor(_RECEIVEDATARESPONSE_TRAVERSALRESPONSESTATUS)

_RESPONSEDATARESPONSE_TRAVERSALRESPONSESTATUS = _descriptor.EnumDescriptor(
  name='TraversalResponseStatus',
  full_name='traversal.ResponseDataResponse.TraversalResponseStatus',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='FOUND', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FORWARDED', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='NOT_FOUND', index=2, number=2,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=265,
  serialized_end=331,
)
_sym_db.RegisterEnumDescriptor(_RESPONSEDATARESPONSE_TRAVERSALRESPONSESTATUS)


_RECEIVEDATAREQUEST = _descriptor.Descriptor(
  name='ReceiveDataRequest',
  full_name='traversal.ReceiveDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='hash_id', full_name='traversal.ReceiveDataRequest.hash_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='traversal.ReceiveDataRequest.request_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='stack', full_name='traversal.ReceiveDataRequest.stack', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='visited', full_name='traversal.ReceiveDataRequest.visited', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='requesting_node_ip', full_name='traversal.ReceiveDataRequest.requesting_node_ip', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=147,
)


_RECEIVEDATARESPONSE = _descriptor.Descriptor(
  name='ReceiveDataResponse',
  full_name='traversal.ReceiveDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='traversal.ReceiveDataResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='file_bytes', full_name='traversal.ReceiveDataResponse.file_bytes', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RECEIVEDATARESPONSE_TRAVERSALRESPONSESTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=331,
)


_RESPONSEDATAREQUEST = _descriptor.Descriptor(
  name='ResponseDataRequest',
  full_name='traversal.ResponseDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_bytes', full_name='traversal.ResponseDataRequest.file_bytes', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='traversal.ResponseDataRequest.request_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='node_ip', full_name='traversal.ResponseDataRequest.node_ip', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='status', full_name='traversal.ResponseDataRequest.status', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='traversal.ResponseDataRequest.path', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=333,
  serialized_end=441,
)


_RESPONSEDATARESPONSE = _descriptor.Descriptor(
  name='ResponseDataResponse',
  full_name='traversal.ResponseDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='traversal.ResponseDataResponse.status', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _RESPONSEDATARESPONSE_TRAVERSALRESPONSESTATUS,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=444,
  serialized_end=607,
)


_SENDDATAREQUEST = _descriptor.Descriptor(
  name='SendDataRequest',
  full_name='traversal.SendDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='file_bytes', full_name='traversal.SendDataRequest.file_bytes', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='request_id', full_name='traversal.SendDataRequest.request_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='client_node_ip', full_name='traversal.SendDataRequest.client_node_ip', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=609,
  serialized_end=690,
)


_SENDDATARESPONSE = _descriptor.Descriptor(
  name='SendDataResponse',
  full_name='traversal.SendDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=692,
  serialized_end=710,
)

_RECEIVEDATARESPONSE.fields_by_name['status'].enum_type = _RECEIVEDATARESPONSE_TRAVERSALRESPONSESTATUS
_RECEIVEDATARESPONSE_TRAVERSALRESPONSESTATUS.containing_type = _RECEIVEDATARESPONSE
_RESPONSEDATARESPONSE.fields_by_name['status'].enum_type = _RESPONSEDATARESPONSE_TRAVERSALRESPONSESTATUS
_RESPONSEDATARESPONSE_TRAVERSALRESPONSESTATUS.containing_type = _RESPONSEDATARESPONSE
DESCRIPTOR.message_types_by_name['ReceiveDataRequest'] = _RECEIVEDATAREQUEST
DESCRIPTOR.message_types_by_name['ReceiveDataResponse'] = _RECEIVEDATARESPONSE
DESCRIPTOR.message_types_by_name['ResponseDataRequest'] = _RESPONSEDATAREQUEST
DESCRIPTOR.message_types_by_name['ResponseDataResponse'] = _RESPONSEDATARESPONSE
DESCRIPTOR.message_types_by_name['SendDataRequest'] = _SENDDATAREQUEST
DESCRIPTOR.message_types_by_name['SendDataResponse'] = _SENDDATARESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ReceiveDataRequest = _reflection.GeneratedProtocolMessageType('ReceiveDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECEIVEDATAREQUEST,
  '__module__' : 'traversal_pb2'
  # @@protoc_insertion_point(class_scope:traversal.ReceiveDataRequest)
  })
_sym_db.RegisterMessage(ReceiveDataRequest)

ReceiveDataResponse = _reflection.GeneratedProtocolMessageType('ReceiveDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECEIVEDATARESPONSE,
  '__module__' : 'traversal_pb2'
  # @@protoc_insertion_point(class_scope:traversal.ReceiveDataResponse)
  })
_sym_db.RegisterMessage(ReceiveDataResponse)

ResponseDataRequest = _reflection.GeneratedProtocolMessageType('ResponseDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDATAREQUEST,
  '__module__' : 'traversal_pb2'
  # @@protoc_insertion_point(class_scope:traversal.ResponseDataRequest)
  })
_sym_db.RegisterMessage(ResponseDataRequest)

ResponseDataResponse = _reflection.GeneratedProtocolMessageType('ResponseDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSEDATARESPONSE,
  '__module__' : 'traversal_pb2'
  # @@protoc_insertion_point(class_scope:traversal.ResponseDataResponse)
  })
_sym_db.RegisterMessage(ResponseDataResponse)

SendDataRequest = _reflection.GeneratedProtocolMessageType('SendDataRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDDATAREQUEST,
  '__module__' : 'traversal_pb2'
  # @@protoc_insertion_point(class_scope:traversal.SendDataRequest)
  })
_sym_db.RegisterMessage(SendDataRequest)

SendDataResponse = _reflection.GeneratedProtocolMessageType('SendDataResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDDATARESPONSE,
  '__module__' : 'traversal_pb2'
  # @@protoc_insertion_point(class_scope:traversal.SendDataResponse)
  })
_sym_db.RegisterMessage(SendDataResponse)



_TRAVERSAL = _descriptor.ServiceDescriptor(
  name='Traversal',
  full_name='traversal.Traversal',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=713,
  serialized_end=955,
  methods=[
  _descriptor.MethodDescriptor(
    name='ReceiveData',
    full_name='traversal.Traversal.ReceiveData',
    index=0,
    containing_service=None,
    input_type=_RECEIVEDATAREQUEST,
    output_type=_RECEIVEDATARESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='RespondData',
    full_name='traversal.Traversal.RespondData',
    index=1,
    containing_service=None,
    input_type=_RESPONSEDATAREQUEST,
    output_type=_RESPONSEDATARESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='SendData',
    full_name='traversal.Traversal.SendData',
    index=2,
    containing_service=None,
    input_type=_SENDDATAREQUEST,
    output_type=_SENDDATARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TRAVERSAL)

DESCRIPTOR.services_by_name['Traversal'] = _TRAVERSAL

# @@protoc_insertion_point(module_scope)
